[package]
name = "toors_core"
version = "0.1.0"
edition = "2021"

[dependencies]
toors = { path = "./toors" }
toors_derive = { path ="./toors_derive" }

[workspace]
members = [
    "toors",
    "toors_derive"
]
resolver = "2"
