[package]
edition = "2024"
name    = "toors_core"
version = "0.1.0"

[dependencies]
inventory    = "0.3.20"
serde        = { version = "1.0.219", features = ["derive"] }
serde_json   = "1.0.140"
tokio        = { version = "1.44.2", features = ["rt-multi-thread", "macros"] }
toors        = { path = "./toors" }
toors_macros = { path = "./toors_macros" }

[workspace]
members  = ["toors", "toors_macros", "examples"]
resolver = "2"
