[package]
name = "examples"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
toors={path="../toors"}
toors_derive={path="../toors_derive"}

[[example]]
name="db"
path="db.rs"

[[example]]
name="in_struct"
path="in_struct.rs"

[[example]]
name="example"
path="example.rs"
