[package]
edition = "2021"
name    = "tools"
version = "0.3.0"

[dependencies]
futures              = "0.3.31"
inventory.workspace  = true
serde.workspace      = true
serde_json.workspace = true
thiserror            = "2.0.12"
tokio                = { workspace = true, features = ["macros", "rt-multi-thread", "time"] }
tokio-test           = "0.4.4"
tools_macros         = { path = "../tools_macros" }

# Optional JSON-Schema support
schemars = { workspace = true, features = ["derive"], optional = true }

[features]
default = []           # lean, no schema generation
schema  = ["schemars"]
