[package]
edition = "2024"
name    = "tools_macros"
version = "0.1.0"

[lib]
proc-macro = true

[dependencies]
inventory   = "0.3.20"                               # to reference the runtime’s inventory type
proc-macro2 = "1"
quote       = "1"
syn         = { version = "2", features = ["full"] }
