[package]
edition = "2021"
name    = "tools_macros"
version = "0.1.0"

[lib]
proc-macro = true

[dependencies]
inventory.workspace = true
proc-macro-error    = "1.0.4"
proc-macro2         = "1.0.95"
quote               = "1.0.40"
syn                 = { version = "2.0.101", features = ["full"] }
