name: Publish
on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
jobs:
  Publish:
    runs-on: ubuntu-latest
    container:
      image: rust:latest
    env:
      CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Publish tools_core
        run: cargo publish -p tools_core
      - name: Publish tools_macros
        run: cargo publish -p tools_macros
      - name: Publish
        run: cargo publish

