name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run src tests
      run: cd src && cargo test --verbose 
    - name: Run tests
      run: cargo test --verbose 
    - name: Run tools_macros tests
      run: cd tools_macros && cargo test --verbose 
    - name: Run tools_core tests
      run: cd tools_core && cargo test --verbose 

